apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: transcript-tester
  description: Transcript-tester openapi specification
spec:
  type: openapi
  owner: dois-backstage
  lifecycle: production
  definition:
    $text: ./transcript-tester.yaml
    #$openapi: ./transcript-tester.yaml
